import { Ambiance } from './types';
import { channels } from './channels';

export const lofi: Ambiance[] = [
  {
    name: 'Relax/Study',
    code: 'jfKfPfyJRdk',
    group: 'Lofi Girl',
    livestream: true,
    channel: channels['Lofi Girl'],
  },
  {
    name: 'Synthwave Radio 🌌',
    code: 'MVPTGNGiI-4',
    group: 'Lofi Girl',
    livestream: true,
    channel: channels['Lofi Girl'],
  },
  {
    name: 'Morning Coffee',
    code: '1fueZCTYkpA',
    group: 'Lofi Girl',
    channel: channels['Lofi Girl'],
  },
  {
    name: 'Cozy Winter',
    code: '_tV5LEBDs7w',
    group: 'Lofi Girl',
    channel: channels['Lofi Girl'],
  },
  {
    name: 'Soothing Breeze',
    code: 'gnZImHvA0ME',
    group: 'Lofi Girl',
    channel: channels['Lofi Girl'],
  },
  {
    name: 'Lazy Sunday',
    code: 'zFhfksjf_mY',
    group: 'Lofi Girl',
    channel: channels['Lofi Girl'],
  },
  {
    name: '1 A.M Study Session',
    code: 'lTRiuFIWV54',
    group: 'Lofi Girl',
    channel: channels['Lofi Girl'],
  },
  {
    name: 'Sleep/Chill',
    code: 'rUxyKA_-grg',
    group: 'Lofi Girl',
    channel: channels['Lofi Girl'],
    livestream: true,
  },
  {
    name: 'Coffee Shop Hip-Hop Beats',
    code: 'e3L1PIY1pN8',
    group: 'Coffee Shop',
    livestream: true,
    channel: channels['STEEZYASFUCK'],
  },
  {
    name: 'lofi Hip-Hop Radio',
    code: 'e3L1PIY1pN8',
    group: 'Lofi',
    livestream: true,
    channel: channels['STEEZYASFUCK'],
  },
  {
    name: 'Rain Lofi',
    code: 'aVNe2w0AljU',
    group: 'Lofi',
    livestream: true,
    channel: channels['lofi geek'],
  },
  {
    name: 'Lofi Cafe',
    code: 'ORBwkXsUNEs',
    group: 'Coffee Shop',
    livestream: true,
    channel: channels['lofi geek'],
  },
  {
    name: 'Nintendo Lofi Study Beats',
    code: '7JMvn0wfABQ',
    group: 'Gaming',
    channel: channels.Helynt,
  },
  {
    name: 'Late Night Gaming - Chill Lofi Beats',
    code: 'pIA9ztlyzMA',
    group: 'Gaming',
    channel: channels.Helynt,
  },
  {
    name: 'Crackling Fireplace',
    code: 'yimlIZEJwPY',
    group: 'Lofi',
    channel: channels['Chillhop Music'],
  },
  {
    name: 'Animal Crossing Lofi Beats',
    code: 'OPVQMGOuMYI',
    group: 'Gaming',
    channel: channels.Helynt,
  },
  {
    name: 'Nintendo Synthwave Mix',
    code: 'jpyMaQ6afLk',
    group: 'Gaming',
    channel: channels.Helynt,
  },
  {
    name: 'Minecraft Lofi Study Beats',
    code: 'RvLk1pGAEqA',
    group: 'Gaming',
    channel: channels.Helynt,
  },
  {
    name: 'Pokémon lofi Beats',
    code: 'vR60tNCGCIE',
    group: 'Gaming',
    channel: channels.Helynt,
  },
  {
    name: 'Chillhop - Jazzy/Lofi hip hop beats',
    code: '5yx6BWlEVcY',
    group: 'Lofi',
    channel: channels['Chillhop Music'],
    livestream: true,
  },
  {
    name: 'lofi hip hop radio',
    code: '7NOSDKb0HlU',
    group: 'Lofi',
    channel: channels['Chillhop Music'],
    livestream: true,
  },
  {
    name: 'japanese night cafe vibes',
    code: '9FvvbVI5rYA',
    group: 'Coffee Shop',
    channel: channels['Chill with Taiki'],
    startTimeS: 5,
  },
  {
    name: 'korean cafe vibes',
    code: 'Xry_g0Vp5MY',
    group: 'Coffee Shop',
    channel: channels['Chill with Taiki'],
  },
  {
    name: '[24/7 study with me] chill study',
    code: 'azV9PMW5-Ro',
    group: 'Study',
    channel: channels['Chill with Taiki'],
    livestream: true,
  },
  {
    name: '24/7 CHILL LOFI HIP HOP RADIO',
    code: 'qH3fETPsqXU',
    group: 'Hip Hop',
    channel: channels['Chill with Taiki'],
    livestream: true,
  },
  {
    name: 'Chill Drive',
    code: 'kMiBrqV_4FA',
    group: 'Hip Hop',
    channel: channels['Chilli Music'],
  },
  {
    name: 'coffee to go! ☕ jazzy lofi beats',
    code: '2gliGzb2_1I',
    group: 'Coffee Shop',
    channel: channels.TheJazzHopCafé,
    livestream: true,
  },
  {
    name: 'Tokyo Lofi Hip Hop',
    code: 'S4f2XYGLoM8',
    group: 'Hip Hop',
    livestream: true,
    channel: channels['lofi geek'],
  },
  {
    name: 'Lofi Space Station',
    code: '3k42V5tkD6s',
    group: 'Space',
    livestream: true,
    channel: channels['lofi geek'],
  },
  {
    name: 'Space Hip Hop',
    code: 'Qt0-9mO-ZXY',
    group: 'Space',
    livestream: true,
    channel: channels['lofi geek'],
  },
  {
    name: 'Overwatch - Lofi',
    code: 'dp4miziEOvQ',
    group: 'Gaming',
    channel: channels['Overwatch League'],
  },
  {
    name: 'Overwatch 2 - Lofi',
    code: 'b_anhQUwD0Q',
    group: 'Gaming',
    channel: channels['Overwatch League'],
  },
  {
    name: 'World of Warcraft - Lofi',
    code: 'UWrslj9JQnc',
    group: 'Gaming',
    channel: channels['World of Warcraft'],
  },
  {
    name: 'Zelda & Chill',
    code: 'GdzrrWA8e7A',
    group: 'Gaming',
    channel: channels.GameChops,
  },
  {
    name: 'Zelda & Chill 2',
    code: 'rJlY1uKL87k',
    group: 'Gaming',
    channel: channels.GameChops,
  },
  {
    name: 'Chilltendo Deluxe',
    code: 'c5V-qL1HRho',
    group: 'Gaming',
    channel: channels.GameChops,
  },
  {
    name: 'Poké & Chill',
    code: '2DVpys50LVE',
    group: 'Gaming',
    channel: channels.GameChops,
  },
  {
    name: 'Video Game Study Lounge',
    code: 'nTdJ0P4fXDg',
    group: 'Gaming',
    livestream: true,
    channel: channels.GameChops,
  },
  {
    name: 'Lord of the Rings',
    code: 'HBpUNPBA_qk',
    group: 'LotR',
    channel: channels['Ambient Worlds'],
  },
  {
    name: 'mellow/chill instrumental beats',
    code: 'QwXHcgZUnFI',
    group: 'Lofi',
    livestream: true,
    channel: channels['College Music'],
  },
  {
    name: 'Good Vibes Only - Hip-Hop',
    code: 'aGSYKFb_zxg',
    group: 'Hip Hop',
    livestream: true,
    channel: channels['LTB Music'],
  },
  {
    name: 'Chill Village - Deep Focus Lofi',
    code: 'cUswBpG0lwY',
    group: 'Lofi',
    livestream: true,
    channel: channels['LTB Music'],
  },
];
